package httpapi

import (
	"context"
	"log/slog"
	"net/http"

	"backend/internal/auth"
	"backend/internal/config"
	inventory "backend/internal/inventory"
	ocr "backend/internal/ocr"
	procurement "backend/internal/procurement"
)

func NewRouter(cfg config.Config, logger *slog.Logger, authService *auth.Service, phaseOne *inventory.Service, phaseTwo *procurement.Service, phaseThree *ocr.Service, readyCheck func(context.Context) error) http.Handler {
	handlers := NewHandlers(cfg, logger, authService, phaseOne, phaseTwo, phaseThree, readyCheck)
	mux := http.NewServeMux()

	mux.HandleFunc("GET /health", handlers.Health)
	mux.HandleFunc("GET /healthz", handlers.Health)
	mux.HandleFunc("GET /ready", handlers.Ready)
	mux.HandleFunc("GET /readyz", handlers.Ready)
	mux.HandleFunc("POST /api/users", handlers.BootstrapRegisterUser)
	mux.HandleFunc("GET /api/health", handlers.APIHealth)
	mux.HandleFunc("GET /api/v1/bootstrap", handlers.Bootstrap)
	mux.HandleFunc("GET /api/v1/auth/me", handlers.CurrentSession)
	mux.HandleFunc("POST /api/v1/auth/register", handlers.RegisterUser)
	mux.HandleFunc("GET /api/v1/operator/requirements", handlers.Requirements)
	mux.HandleFunc("POST /api/v1/operator/requirements", handlers.UpsertRequirement)
	mux.HandleFunc("GET /api/v1/operator/dashboard", handlers.OperatorDashboard)
	mux.HandleFunc("GET /api/v1/operator/reservations", handlers.ReservationList)
	mux.HandleFunc("GET /api/v1/operator/reservations/{id}", handlers.ReservationDetail)
	mux.HandleFunc("PATCH /api/v1/operator/reservations/{id}", handlers.UpdateReservation)
	mux.HandleFunc("DELETE /api/v1/operator/reservations/{id}", handlers.DeleteReservation)
	mux.HandleFunc("POST /api/v1/operator/reservations/{id}/allocate", handlers.AllocateReservation)
	mux.HandleFunc("POST /api/v1/operator/reservations/{id}/release", handlers.ReleaseReservation)
	mux.HandleFunc("POST /api/v1/operator/reservations/{id}/fulfill", handlers.FulfillReservation)
	mux.HandleFunc("POST /api/v1/operator/reservations/{id}/cancel", handlers.CancelReservation)
	mux.HandleFunc("POST /api/v1/operator/reservations/{id}/undo", handlers.UndoReservation)
	mux.HandleFunc("GET /api/v1/operator/shortages", handlers.ShortageList)
	mux.HandleFunc("GET /api/v1/operator/shortages/export", handlers.ShortageCSVExport)
	mux.HandleFunc("GET /api/v1/operator/imports", handlers.ImportHistory)
	mux.HandleFunc("GET /api/v1/operator/imports/{id}", handlers.ImportDetail)
	mux.HandleFunc("POST /api/v1/operator/imports/{id}/undo", handlers.UndoImport)
	mux.HandleFunc("POST /api/v1/operator/reservations", handlers.CreateReservation)
	mux.HandleFunc("GET /api/v1/inventory/overview", handlers.InventoryOverview)
	mux.HandleFunc("GET /api/v1/inventory/snapshot", handlers.InventorySnapshot)
	mux.HandleFunc("GET /api/v1/inventory/items", handlers.InventoryItems)
	mux.HandleFunc("GET /api/v1/inventory/locations", handlers.InventoryLocations)
	mux.HandleFunc("GET /api/v1/inventory/events", handlers.InventoryEvents)
	mux.HandleFunc("POST /api/v1/inventory/receives", handlers.ReceiveInventory)
	mux.HandleFunc("POST /api/v1/inventory/movements", handlers.MoveInventory)
	mux.HandleFunc("POST /api/v1/inventory/events/{id}/undo", handlers.UndoInventoryEvent)
	mux.HandleFunc("POST /api/v1/inventory/adjustments", handlers.AdjustInventory)
	mux.HandleFunc("GET /api/v1/inspector/arrivals", handlers.Arrivals)
	mux.HandleFunc("POST /api/v1/inspector/receipts", handlers.CreateReceipt)
	mux.HandleFunc("POST /api/v1/inventory/receipts", handlers.CreateReceipt)
	mux.HandleFunc("GET /api/v1/admin/master-data", handlers.MasterSummary)
	mux.HandleFunc("GET /api/v1/admin/master-data/export", handlers.MasterDataExport)
	mux.HandleFunc("GET /api/v1/admin/master-data/items", handlers.MasterItems)
	mux.HandleFunc("GET /api/v1/admin/master-data/items/{id}", handlers.MasterItemDetail)
	mux.HandleFunc("POST /api/v1/admin/master-data/items", handlers.UpsertMasterItem)
	mux.HandleFunc("DELETE /api/v1/admin/master-data/items/{id}", handlers.DeleteMasterItem)
	mux.HandleFunc("GET /api/v1/admin/master-data/suppliers", handlers.Suppliers)
	mux.HandleFunc("POST /api/v1/admin/master-data/suppliers", handlers.UpsertSupplier)
	mux.HandleFunc("GET /api/v1/admin/master-data/aliases", handlers.Aliases)
	mux.HandleFunc("POST /api/v1/admin/master-data/aliases", handlers.UpsertAlias)
	mux.HandleFunc("GET /api/v1/admin/master-data/devices", handlers.Devices)
	mux.HandleFunc("POST /api/v1/admin/master-data/devices", handlers.UpsertDevice)
	mux.HandleFunc("GET /api/v1/admin/master-data/scopes", handlers.DeviceScopes)
	mux.HandleFunc("POST /api/v1/admin/master-data/scopes", handlers.UpsertDeviceScope)
	mux.HandleFunc("POST /api/v1/admin/master-data/locations", handlers.UpsertLocation)
	mux.HandleFunc("POST /api/v1/admin/master-data/import/preview", handlers.ImportPreview)
	mux.HandleFunc("POST /api/v1/admin/master-data/import", handlers.MasterDataImport)
	mux.HandleFunc("GET /api/v1/admin/users", handlers.Users)
	mux.HandleFunc("GET /api/v1/admin/users/{id}/history", handlers.UserStatusHistory)
	mux.HandleFunc("GET /api/v1/admin/roles", handlers.Roles)
	mux.HandleFunc("GET /api/v1/admin/permissions", handlers.Permissions)
	mux.HandleFunc("PUT /api/v1/admin/roles/{key}/permissions", handlers.UpdateRolePermissions)
	mux.HandleFunc("POST /api/v1/admin/users/{id}/approve", handlers.ApproveUser)
	mux.HandleFunc("POST /api/v1/admin/users/{id}/reject", handlers.RejectUser)
	mux.HandleFunc("GET /api/v1/procurement/projects", handlers.ProcurementProjects)
	mux.HandleFunc("POST /api/v1/procurement/projects/refresh", handlers.RefreshProcurementProjects)
	mux.HandleFunc("GET /api/v1/procurement/budget-categories", handlers.ProcurementBudgetCategories)
	mux.HandleFunc("POST /api/v1/procurement/budget-categories/refresh", handlers.RefreshProcurementBudgetCategories)
	mux.HandleFunc("GET /api/v1/procurement/sync-runs", handlers.ProcurementSyncRuns)
	mux.HandleFunc("GET /api/v1/procurement/webhooks/external", handlers.ProcurementWebhookEvents)
	mux.HandleFunc("GET /api/v1/procurement/requests", handlers.ProcurementRequests)
	mux.HandleFunc("GET /api/v1/procurement/orders", handlers.ProcurementOrders)
	mux.HandleFunc("GET /api/v1/procurement/orders/{id}", handlers.ProcurementOrderDetail)
	mux.HandleFunc("POST /api/v1/procurement/requests", handlers.CreateProcurementRequest)
	mux.HandleFunc("POST /api/v1/procurement/orders", handlers.CreateProcurementOrder)
	mux.HandleFunc("PATCH /api/v1/procurement/requests/{id}", handlers.UpdateProcurementRequest)
	mux.HandleFunc("PATCH /api/v1/procurement/orders/{id}", handlers.UpdateProcurementOrder)
	mux.HandleFunc("DELETE /api/v1/procurement/orders/{id}", handlers.DeleteProcurementOrder)
	mux.HandleFunc("GET /api/v1/procurement/requests/", handlers.ProcurementRequestDetail)
	mux.HandleFunc("POST /api/v1/procurement/requests/{id}/submit", handlers.SubmitProcurementRequest)
	mux.HandleFunc("POST /api/v1/procurement/requests/{id}/reconcile", handlers.ReconcileProcurementRequest)
	mux.HandleFunc("POST /api/v1/procurement/webhooks/external", handlers.ProcurementWebhook)
	mux.HandleFunc("GET /api/v1/procurement/ocr-jobs", handlers.OCRJobList)
	mux.HandleFunc("POST /api/v1/procurement/ocr-jobs", handlers.CreateOCRJob)
	mux.HandleFunc("GET /api/v1/procurement/ocr-jobs/{id}", handlers.OCRJobDetail)
	mux.HandleFunc("PATCH /api/v1/procurement/ocr-jobs/{id}/review", handlers.UpdateOCRReview)
	mux.HandleFunc("POST /api/v1/procurement/ocr-jobs/{id}/assist", handlers.AssistOCRLine)
	mux.HandleFunc("POST /api/v1/procurement/ocr-jobs/{id}/create-draft", handlers.CreateOCRProcurementDraft)
	mux.HandleFunc("POST /api/v1/procurement/ocr-jobs/{id}/retry", handlers.RetryOCRJob)
	mux.HandleFunc("PUT /api/v1/procurement/ocr-jobs/{id}/register-item", handlers.RegisterOCRItem)

	var handler http.Handler = mux
	if authService != nil {
		handler = authService.Middleware(handler)
	}
	handler = WithCORS(handler, cfg.HTTP.AllowedOrigins)
	handler = WithRequestID(handler)
	handler = WithAccessLog(handler, logger)
	handler = WithRecover(handler, logger)
	return handler
}
