import {
  ClipboardList,
  CalendarCheck,
  AlertTriangle,
  Upload,
  History,
  Package,
  MapPin,
  ArrowRightLeft,
  FileText,
  ScanLine,
  Truck,
  Users,
  Shield,
  Database,
  GitBranch,
  Calendar,
} from 'lucide-react'
import type { RouteDefinition } from '../types'

export const routes: RouteDefinition[] = [
  {
    app: 'operator',
    path: '/app/operator/scopes',
    label: 'Scope Overview',
    description: 'Scope tree with summary counts',
    roles: ['operator', 'inventory', 'admin'],
    icon: GitBranch,
  },
  {
    app: 'operator',
    path: '/app/operator/requirements',
    label: 'Requirements',
    description: 'Requirements and shortage overview',
    roles: ['operator', 'admin'],
    icon: ClipboardList,
  },
  {
    app: 'operator',
    path: '/app/operator/reservations',
    label: 'Reservations',
    description: 'Reservation list and stock allocation',
    roles: ['operator', 'inventory', 'admin'],
    icon: CalendarCheck,
  },
  {
    app: 'operator',
    path: '/app/operator/shortage',
    label: 'Shortage',
    description: 'Shortage analysis and CSV export',
    roles: ['operator', 'inventory', 'admin'],
    icon: AlertTriangle,
  },
  {
    app: 'operator',
    path: '/app/operator/imports/upload',
    label: 'Imports Upload',
    description: 'Upload and stage CSV imports',
    roles: ['operator', 'admin'],
    icon: Upload,
  },
  {
    app: 'operator',
    path: '/app/operator/imports/history',
    label: 'Imports History',
    description: 'Track import jobs and outcomes',
    roles: ['operator', 'admin'],
    icon: History,
  },
  {
    app: 'inventory',
    path: '/app/inventory/items',
    label: 'Items',
    description: 'Item-based inventory balances',
    roles: ['inventory', 'admin'],
    icon: Package,
  },
  {
    app: 'inventory',
    path: '/app/inventory/locations',
    label: 'Locations',
    description: 'Location-based inventory view',
    roles: ['inventory', 'admin'],
    icon: MapPin,
  },
  {
    app: 'inventory',
    path: '/app/inventory/events',
    label: 'Events',
    description: 'Receive, move, and adjust inventory',
    roles: ['inventory', 'admin'],
    icon: ArrowRightLeft,
  },
  {
    app: 'inventory',
    path: '/app/inventory/arrivals/calendar',
    label: 'Arrival Calendar',
    description: 'Expected arrivals by date',
    roles: ['inventory', 'receiving_inspector', 'admin'],
    icon: Calendar,
  },
  {
    app: 'procurement',
    path: '/app/procurement/requests',
    label: 'Requests',
    description: 'Procurement request list',
    roles: ['procurement', 'admin'],
    icon: FileText,
  },
  {
    app: 'procurement',
    path: '/app/procurement/ocr-queue',
    label: 'OCR Queue',
    description: 'Quotation upload and OCR review',
    roles: ['procurement', 'admin'],
    icon: ScanLine,
  },
  {
    app: 'inspector',
    path: '/app/inspector/arrivals',
    label: 'Arrivals',
    description: 'Receipt confirmation and inspection',
    roles: ['receiving_inspector', 'admin'],
    icon: Truck,
  },
  {
    app: 'admin',
    path: '/app/admin/users',
    label: 'Users',
    description: 'Registration approval and accounts',
    roles: ['admin'],
    icon: Users,
  },
  {
    app: 'admin',
    path: '/app/admin/roles',
    label: 'Roles',
    description: 'Role catalog and permissions',
    roles: ['admin'],
    icon: Shield,
  },
  {
    app: 'admin',
    path: '/app/admin/master',
    label: 'Master Data',
    description: 'Items, suppliers, aliases',
    roles: ['admin'],
    icon: Database,
  },
]

export const APP_SECTION_LABELS: Record<string, string> = {
  operator: 'Operator',
  inventory: 'Inventory',
  procurement: 'Procurement',
  inspector: 'Inspector',
  admin: 'Admin',
}
