import type { RouteDefinition } from '../types'

export const routes: RouteDefinition[] = [
  {
    app: 'operator',
    path: '/operator/dashboard',
    label: 'Requirements',
    description: 'Requirements and shortage overview',
    roles: ['operator', 'admin'],
  },
  {
    app: 'operator',
    path: '/operator/reservations',
    label: 'Reservations',
    description: 'Reservation list and stock allocation status',
    roles: ['operator', 'inventory', 'admin'],
  },
  {
    app: 'operator',
    path: '/operator/shortages',
    label: 'Shortages',
    description: 'Projection-based shortage list and import history',
    roles: ['operator', 'inventory', 'admin'],
  },
  {
    app: 'inventory',
    path: '/inventory/stock',
    label: 'Stock',
    description: 'Balances by item and location',
    roles: ['inventory', 'admin'],
  },
  {
    app: 'inventory',
    path: '/inventory/events',
    label: 'Events',
    description: 'Receive, move, and adjust inventory',
    roles: ['inventory', 'admin'],
  },
  {
    app: 'operator',
    path: '/operator/imports/upload',
    label: 'Imports Upload',
    description: 'Upload and stage CSV imports',
    roles: ['operator', 'admin'],
  },
  {
    app: 'operator',
    path: '/operator/imports/history',
    label: 'Imports History',
    description: 'Track import jobs and outcomes',
    roles: ['operator', 'admin'],
  },
  {
    app: 'procurement',
    path: '/procurement/requests',
    label: 'Requests',
    description: 'Draft and submitted procurement requests',
    roles: ['procurement', 'admin'],
  },
  {
    app: 'procurement',
    path: '/procurement/ocr',
    label: 'OCR Queue',
    description: 'Quotation upload and OCR review queue',
    roles: ['procurement', 'admin'],
  },
  {
    app: 'inspector',
    path: '/inspector/arrivals',
    label: 'Arrivals',
    description: 'Receipt confirmation and inspection',
    roles: ['receiving_inspector', 'admin'],
  },
  {
    app: 'admin',
    path: '/admin/users',
    label: 'Users',
    description: 'Registration approval and account status',
    roles: ['admin'],
  },
  {
    app: 'admin',
    path: '/admin/roles',
    label: 'Roles',
    description: 'Role catalog and routing matrix',
    roles: ['admin'],
  },
  {
    app: 'admin',
    path: '/admin/master-data',
    label: 'Master Data',
    description: 'Users, items, suppliers, aliases',
    roles: ['admin'],
  },
]
